### ISSUE TITLE
프로그램 강제 종료 문제

### ISSUE THREAD

**Issue by rainmaker64** [argosdyne/Parameter_Compare#1]
금일 테스트 프로그램으로 테스트시 프로그램이 종료되는 문제가 있어 매일 드립니다.

프로그램에 입력한 파일 캡쳐 사진 입니다.

아래 사진 참조 바랍니다.

감사 합니다.

간단한 설명서를 첨부 해 주시면 추가 확인 하도록 하겠습니다.
![pic01](https://user-images.githubusercontent.com/91441739/142787311-e4f11159-bf0a-44c5-ac70-d3c9594d27cc.png)

**Comment by leesuann** [comment]
강제 종료 문제 해결한 코드 올렸습니다.
