### ISSUE TITLE
비교시 종료되는 현상

### ISSUE THREAD

**Issue by frozenof** [argosdyne/Parameter_Compare#3]
비교프로그램 사용시, targetparam에 어떤 기체의 파라미터를 넣고 비교할 경우 강제종료되는 현상이 있습니다.
해당 타겟 파라미터파일은 업로드한 파일에 압축하여 넣었습니다. (파일명: Aq13Uneec.param)

프로세스
1. 해당 파일을 압축을 풀고 실행파일을 실행
2. 각 파라미터 파일을 할당시킨다.
refparam - ref-Aquila.param, 
targetparam - Aq13Uneec.param
check - checks.param
ignores - ignores.param
3. 비교하기를 누르면 강제종료 됨

![image](https://user-images.githubusercontent.com/91515841/142816698-3ae80232-f7a6-4778-88eb-05e407018787.png)

[ParamComp.zip](https://github.com/argosdyne/Parameter_Compare/files/7578718/ParamComp.zip)

**Comment by leesuann** [comment]
강제 종료 현상이 일어나는 이슈 해결한 코드 올렸습니다.
